# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 03:48
from __future__ import unicode_literals

from django.db import migrations


def add_boards(apps, schema_editor):
    Board = apps.get_model("main", "Board")
    ALL_BOARDS = [
            ("a", "Anime"),
            ("b", "Random"),
            ("g", "Technology"),
            ("gif", "Adult Gif/Webm"),
            ("e", "Ecchi"),
            ("h", "Hentai"),
            ("r", "Requests"),
            ("sci", "Science"),
            ("soc", "Social"),
            ("v", "Video Games"),
            ("wsg", "Work-safe Gif"),]
    for board in ALL_BOARDS:
        Board.objects.create(fullname=board[1], charname=board[0])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_boards)
    ]
